### ISSUE TITLE
Stuck on "rewrite -> ..." tactic

### ISSUE THREAD

**Issue by Guest0x0** [LumaKernel/coqpit.vim#1]
First my great appreciation to this awesome plugin, which finally get my neovim play well with Coq.

I am using neovim 0.4.3, coq 8.11.0 (OCaml 4.09.0), with coqidetop available. The coquille plugin is installed via
```
Plug 'LumaKernel/coquille'
```
and is up-to-date w.r.t vim-plug.
All options are not modified.

The issue is that coquille will eat up 100% CPU and cause neovim stuck (not responding) when performing `CoqNext` or `CoqToCursor` on a tactic call of the from `rewrite -> ...`.
Here's an example to reproduce it:
```coq
From Coq Require Import Arith.Plus.
Theorem a : forall n : nat, plus n O = n.
Proof.
  intros n.
  rewrite -> plus_n_O.
  reflexivity.
Qed.
```
And the issue occurs when executing the 5th line.
Weird enough, the issue can be avoided by:

> 1. simply remove the '->' (`rewrite plus_n_O.`)

> 2. revert the equation, either by adding a `symmetry.` line or directly modifying the theorem, and use `rewrite <- plus_n_O.`

With either of the above 2 modifications, the plugin works fine without any problems.
BTW, *coqtop* and *coqide* don't have the same issue.

**Comment by ghost** [comment]
Thanks for your polite issue !
I may have fixed.

**Comment by Guest0x0** [comment]
Yes, I can confirmed that is is now fixed on my setup. Thanks for your quick response ;)
